version: '3.8'

services:
  app:
    build: .
    image: laravelapp 
    entrypoint:  ["/bin/bash","/projet/entrypoint.sh"]  
    ports:
      - "7000:8000"
    volumes:
      - ./app:/projet
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db

  db:
    image: postgres:15
    
    restart: always
    # environment:
    #   POSTGRES_USER: laravel
    #   POSTGRES_PASSWORD: laravel
    #   POSTGRES_DB: laravel_db
    volumes:
      - db_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

volumes:
  db_data:
